# Generated by Django 4.2.2 on 2023-06-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('MIDFIELD', 'Midfield'), ('DEFENDER', 'Defender'), ('STRIKER', 'Striker'), ('GOALKEEPER', 'Goalkeeper')], max_length=10, null=True),
        ),
    ]
